/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.terminal_end.scraper

import org.junit.Test
import org.junit.Assert.*

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod())
    }
}
