/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package net.terminal_end.scraper;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
